### ISSUE TITLE
No map is displayed in rviz

### ISSUE THREAD

**Issue by yangjiongfeng** [hyye/lio-mapping#10]
hello 
i have been run 
1.roslaunch lio test_indoor.launch 
2.roslaunch lio map_4D_indoor.launch 
3.rosbag play fast1.bag
but ,No map is displayed in rviz
What's wrong with me?

**Comment by hyye** [comment]
I guess it could related to the communication problem in `ROS`. Could you close all your launches and start `roscore` first, before you start other launches and `rosbag`? 
`rostopic` or `rqt_graph` commands can also help you debug with this problem.

BTW, please make sure the code is built with `Release` option.

**Comment by yangjiongfeng** [comment]
I have been restart many times，
But as a result, also no map was displayed on rviz 。
What's your WeChat or Email  number?

**Comment by hyye** [comment]
Can you make sure if you build the code with **`Release`** option? As I replied here https://github.com/hyye/lio-mapping/issues/2#issuecomment-488046749.

**Comment by hyye** [comment]
Try to use `catkin build -DCMAKE_BUILD_TYPE=Release lio` or `catkin_make -DCMAKE_BUILD_TYPE=Release` to rebuild the project.

**Comment by yangjiongfeng** [comment]
Thank you！
when i try to use catkin build -DCMAKE_BUILD_TYPE=Release ，I've solved the problem 。
why you project need use catkin build -DCMAKE_BUILD_TYPE=Release but not catkin_make?

**Comment by hyye** [comment]
Glad to help!
It is not `catkin build` or `catkin_make` making differences, but the `CMAKE_BUILD_TYPE`.
Typically, `catkin build` or `catkin_make` will not trigger the `Release` flag.

**Comment by yangjiongfeng** [comment]
i have build map use you code.
now,i run rosrun rqt_tf_tree rqt_tf_tree,can show de tf_tree
![选区_006](https://user-images.githubusercontent.com/27730697/60639311-b0133100-9e54-11e9-8876-00df33179227.png)
and then,i run rqt_graph
show 
![选区_011](https://user-images.githubusercontent.com/27730697/60639377-01bbbb80-9e55-11e9-9e0b-c393f5b41dd2.png)
only /local/full_point between lio_estimator and lio_map_builder,
but you code have four subscribe
![选区_010](https://user-images.githubusercontent.com/27730697/60639498-7c84d680-9e55-11e9-98c2-ac8b473e7b59.png)

why build the map only use one subscribe？

**Comment by hyye** [comment]
It should be four instead of only one, if it run properly.
Maybe some of the  programs (nodes) are exited.
