### ISSUE TITLE
Playing my data set after 20 secs lio_processor died

### ISSUE THREAD

**Issue by llu0120** [hyye/lio-mapping#14]
Hi author, 
I run the open source on my own data, 
first I run `roslaunch lio test_indoor.launch &` and then run `roslaunch lio map_4D_indoor.launch &`. After these command, I play my bag by adding `--clock` at the end and after running for 20 sec, the process is died like below. 
![Selection_006](https://user-images.githubusercontent.com/41609738/61125825-7211af00-a4dd-11e9-8d4a-338dab8d134a.png)
However, if I don't add `--clock ` at the end, the process will not died in the whole bag, but the terminal of `roslaunch lio test_indoor.launch &` didn't show anything and also nothing shown in rviz as well. Any suggestions for this bug? Thank you!

**Comment by hyye** [comment]
Did you use self-collected data?

I didn't meet this problem. I don't think it is a common "bug". With only error information from the terminal, it is tough to say where the problem is.
As I said before, using gdb to find out where the program dies can help us to locate the problem.

**Comment by llu0120** [comment]
Thanks for your reply! 
I use gdb and the result looks like below:
![Selection_008](https://user-images.githubusercontent.com/41609738/61192105-7cea6080-a6e4-11e9-8a9b-cb0e63a5f107.png)
![Selection_009](https://user-images.githubusercontent.com/41609738/61192107-7f4cba80-a6e4-11e9-879c-572fa230d0ee.png)

**Comment by hyye** [comment]
Does the provided dataset work?
It seems some problems with `PointProcess`. Is there any NAN data in your point cloud? If yes, maybe try to filter the NAN data.

But, I believe it is a problem with some libraries. My suggestion is to clean and rebuild the project first.

BTW, what is your `PCL`, `Eigen` and `gcc` version?

**Comment by llu0120** [comment]
The provided dataset printed out the messages without errors like below 
![Selection_010](https://user-images.githubusercontent.com/41609738/61196425-2b9c9a00-a701-11e9-92d5-a4d861c799ff.png)
However, Rviz didn't show any topics visualization like below 
![Selection_011](https://user-images.githubusercontent.com/41609738/61196442-40792d80-a701-11e9-8295-d94c6faa9266.png)
and my `PCL `version is 1.8.0, `Eigen` is 3.2.92, `gcc` is 5.4.0.

**Comment by hyye** [comment]
There are no results since it was not built with `Release` option. See https://github.com/hyye/lio-mapping/issues/2#issuecomment-508306469 and https://github.com/hyye/lio-mapping/issues/10#issuecomment-508308072.

**Comment by llu0120** [comment]
But if I build with Release option, the process estimator will died like below
![Selection_012](https://user-images.githubusercontent.com/41609738/61196662-d19cd400-a702-11e9-9548-67e228a95ace.png)

**Comment by hyye** [comment]
Then, I am not sure where the problem is, potentially related to some libraries. My final recommendation is to use `docker` or another computer to see if the same problem exists.

**Comment by llu0120** [comment]
Thanks for the suggestion! However, because of being new to using docker, are there any instruction to setup the environment?

**Comment by hyye** [comment]
I suggest to follow [docker docs](https://docs.docker.com/install/linux/docker-ce/ubuntu/) and [nvidia-docker wiki](https://github.com/nvidia/nvidia-docker/wiki/Installation-(version-2.0)) to setup the basic docker environment.

Then, use the commands I provided in the [README](https://github.com/hyye/lio-mapping#docker) to build and run docker. I hope this can help you.

**Comment by llu0120** [comment]
When I tried the command `sudo apt-get install nvidia-docker2`, some problem happened like below,
![Selection_018](https://user-images.githubusercontent.com/41609738/61216866-fe6fdc00-a740-11e9-9c9a-c2ec38aba98c.png)
I Googled it but still couldn't fix it, can you help me? Thank you!

**Comment by llu0120** [comment]
Now my docker version is `Docker version 18.09.7, build 2d0083d` and I have install nvidia-docker2 by `sudo apt-get install -y nvidia-docker2 ` and  `pkill -SIGHUP dockerd` successfully. What is the next step, how to run your readme command `docker/build_docker.sh`, I run like below but it didn't pass. 
![Selection_018](https://user-images.githubusercontent.com/41609738/61219514-f5820900-a746-11e9-821c-5348cfaf97b5.png)

**Comment by hyye** [comment]
Well, you need to run the command in the directory `lio-mapping`.

**Comment by llu0120** [comment]
Hi thanks for your instruction, I successfully run your provided dataset with docker. But now I try to plugin my dataset, but the process died again like below. :(
![Selection_021](https://user-images.githubusercontent.com/41609738/61262067-80e6b300-a7b6-11e9-823d-d629507592f5.png)

**Comment by hyye** [comment]
Does the provided dataset work?
Maybe try to check the `NAN` values or incompatible data first. The default rate of 3D lidar is 10Hz.

In docker, you can still use some commands like `docker exec` to enable `gdb`. It seems a problem related to memory corruption.

**Comment by llu0120** [comment]
Yeah it works. But my dataset doesn't, does this mean I need to change the default rate of the 3D lidar compatible to my dataset. I enable the `removeNaNFromPointCloud` first to avoid nan values.

**Comment by hyye** [comment]
If it is standard 3D lidar, like Velodyne, with default settings and drivers. The data should be OK.
It should be a sweep of points (> ten thousand points) in one point cloud with update rate around 10Hz.

**Comment by llu0120** [comment]
Still stuck at this memory corruption problem. It is a standard 3D lidar and I found the difference between my bag and the bags you provide that my `/imu/data` is with frequency 50 Hz but your bags are 400 Hz. Will it be a reason? The ROS messages are normal for the first iteration passing `/laser_cloud_sharp` at 10 hz for two times and passing `/local/surf_points` at 5 hz for one time, but after that the memory corruption problem happens.
Below is another comparison of the `rqt_graphs`.

![Selection_022](https://user-images.githubusercontent.com/41609738/61616734-d67dfc80-ac9b-11e9-8d9b-577bf7089843.png)
![lio-mapping_opensource_rqt](https://user-images.githubusercontent.com/41609738/61616749-dda50a80-ac9b-11e9-94ff-74a603165ba6.png)

**Comment by llu0120** [comment]
I use `gdb` to debug and found that when confronting this line `curvature_idx_pairs_.resize(region_size);` in the `PrepareSubregion` function many times, it will crash with the `memory corruption` error. Any idea why this happened?

**Comment by KitKat7** [comment]
Can you check the `region_size`? Is it too large or invalid?

**Comment by hyye** [comment]
Can you check the `region_size`? Is it too large or invalid?

**Comment by llu0120** [comment]
Thanks for your reply. The value of the `region_size` were around 200 for the first few scan, but then it has suddenly increase to 633 (looks too large but this depends on the `scan_size`), which also corrupt at this point. As the `region_size` is define by `ep` `sp` and those two are define by `scan_size`, but the `scan_size` are the data grab from my lidar, so I don't think I can change that. Any suggestion?  By the way, my lidar is not a Velodyne, it is a Pandar.

**Comment by hyye** [comment]
BTW, what is your platform? Does it have enough memory to run the program?
One suggestion is to add some [exception handling](https://docs.microsoft.com/en-us/cpp/cpp/try-throw-and-catch-statements-cpp?view=vs-2019) to enclose the line causing the problem.

But it can still relate to the driver or data.
I haven't tried Pandar. The current version does not directly support lidars that are not with 16, 32, or 64 scans.

**Comment by llu0120** [comment]
Thanks Author, 
I have solve this problem for changing the computation of `ElevationToRing` since my lidar is different than yours.
