### ISSUE TITLE
Hello, why is rviz no point cloud display?

### ISSUE THREAD

**Issue by hunkyu** [hyye/lio-mapping#2]
![Screenshot from 2019-05-01 01-03-50](https://user-images.githubusercontent.com/20533364/56979801-30938800-6bad-11e9-9cb5-0349732a2729.png)
![Screenshot from 2019-05-01 01-04-15](https://user-images.githubusercontent.com/20533364/56979811-34bfa580-6bad-11e9-99ae-f1a800856944.png)
I am using fast1.bag but no rviz has no point cloud display

**Comment by hyye** [comment]
Hi @hunkyu, can you check if you build with the flag `-DCMAKE_BUILD_TYPE=Release`? If not, the runtime cannot be ensured and the estimator might not be initialized well. This debug info should not appear with release compilation. The default flag will be added in the `CMakeLists.txt` the future release.

**Comment by yangjiongfeng** [comment]
I have the same problem as you.
Have you solved the problem yet?

**Comment by RalphCodesTheInternet** [comment]
Same problem. Any solutions yet?
