### ISSUE TITLE
Advice for tuning in large environments

### ISSUE THREAD

**Issue by andre-nguyen** [hyye/lio-mapping#20]
LIO becomes very slow in my large environment, to a point where I have to pause my bag file to give LIO time to catch up. 

![image](https://user-images.githubusercontent.com/6036318/61745537-c16e9f80-ad67-11e9-8d1e-881b96b98228.png)

Do you have any advice on how to tune the parameters to keep things running smoothly or constrain processing time?

I would also be interested in some documentation on the following parameters:

* `msg_time_delay`
* `cutoff_deskew`
* `init_window_factor`
* `update_laser_imu`

**Comment by hyye** [comment]
If there are too many lidar feature points, the processing time would be longer. Maybe consider reducing the window sizes or feature points. For configuration, the outdoor config can be a reference.

`msg_time_delay`: the time offset between lidar and IMU, for typical Velodyne data, buffer the IMU to the middle timestamp of the point cloud.
`cutoff_deskew`: turn off deskewing, when using corrected point cloud data, like KITTI.
`init_window_factor`: a factor makes the local window of initialization longer.
`update_laser_imu`: update the optimized states, just for debugging.
