### ISSUE TITLE
Details on jacobian of point to plane factor

### ISSUE THREAD

**Issue by andre-nguyen** [hyye/lio-mapping#25]
Hi,

would it be possible to give the derivation for the jacobians of the point to plane factor? I am a bit confused on how to find the Jacobians from equations (3) and (4) and how the jacobian matrix is 7 x 3.

Thanks,

**Comment by hyye** [comment]
Because our transform is represented in the form of vector (3 elements) and quaternion (4 elements), and the residual is related to 1. frame Lp, 2. frame Lα, and 3. the extrinsic parameter.

**Comment by andre-nguyen** [comment]
@hyye I'm still trying to properly derive the analytical expressions I read "A primer on the Differential Calculus of 3D orientations" but I am a bit unclear on how to properly apply the chain rule and the product rule. Here is what I can understand:

![image](https://user-images.githubusercontent.com/6036318/63199741-c532d080-c04c-11e9-8423-187c5e831053.png)

I believe I have the correct expressions for the position derivatives:

![image](https://user-images.githubusercontent.com/6036318/63199758-d845a080-c04c-11e9-80fe-e4f57f9abff6.png)

But I have a hard time obtaining the same thing you have for the rotations

![image](https://user-images.githubusercontent.com/6036318/63199781-e98ead00-c04c-11e9-8e9f-d1a984db1c9f.png)

For (10) I am missing negative signs on the skew terms. For 11 I have R_{B_\alpha}^{W} inside the skew operator instead of outside. For (12) I have a similar problem where I am unsure how to apply the chain rule. I have tried using first principles and applying a disturbance onto the rotation however I still do not get the same results you do. Would it be possible to show your analytical derivation?

**Comment by hyye** [comment]
Hi @andre-nguyen, in this work, we use the update of rotation on the right side, which may cause the differences in (10) and (11).
For (12), I believe you are very close to the final results by applying a disturbance to the rotation and omitting the high-order terms.

**Comment by andre-nguyen** [comment]
> we use the update of rotation on the right side

Thanks, I understand now, I was adding my pertubation on the left but now that I add the pertubation on the right using
![image](https://user-images.githubusercontent.com/6036318/63457357-e4e84100-c41e-11e9-8a12-cf65b4fd5662.png)
I get the same derivatives except for the last one
![image](https://user-images.githubusercontent.com/6036318/63457436-0e08d180-c41f-11e9-8d42-5f73278049a8.png)
Which matches the code
https://github.com/hyye/lio-mapping/blob/8485a4d9c359b7e486ad019a10815ecb8fd1257f/src/factor/PivotPointPlaneFactor.cc#L86-L88

I also get the same expression for the 2nd jacobian
![image](https://user-images.githubusercontent.com/6036318/63457761-938c8180-c41f-11e9-91da-6680a3c48fff.png)

Which is equivalent to the code here if you distribute the minus sign into the cross operator.
https://github.com/hyye/lio-mapping/blob/8485a4d9c359b7e486ad019a10815ecb8fd1257f/src/factor/PivotPointPlaneFactor.cc#L100-L102

However for the last jacobian wrt R_lidar_body I have an extra term at the end
![image](https://user-images.githubusercontent.com/6036318/63458392-be2b0a00-c420-11e9-9705-5b546b7bc90f.png)

And in the code there is no `-SkewSymmetric(tlb)` term.
https://github.com/hyye/lio-mapping/blob/8485a4d9c359b7e486ad019a10815ecb8fd1257f/src/factor/PivotPointPlaneFactor.cc#L125-L129

Did I make a mistake in the derivation or is there a mistake in the code? I ran the code with the extra term and I'm not sure I can see a difference.

**Comment by hyye** [comment]
I think that in Eqn. (6) of your derivation, R^L_B should time the first two items but not P^L_B.

**Comment by andre-nguyen** [comment]
I'm not sure why you say that but thank you for your time.

**Comment by andre-nguyen** [comment]
OK I double checked and you are right, it should not be multiplied.
Thank you!

The correct residual term is thus 
![image](https://user-images.githubusercontent.com/6036318/63784099-1c8e3780-c8bc-11e9-9063-d4e37176334f.png) 

and now all my equations match.
