### ISSUE TITLE
some parameter and extrinsic calibration

### ISSUE THREAD

**Issue by yuer-h** [hyye/lio-mapping#26]
hello , hyye !  I have some question and need your help.
1、In the outdoor.yaml , the parameter window_size , opt_size .  If I set it larger or smaller , what it would be influence ?  In other word, how to debug the parameter .
2、Why extrinsic calibration only calibrate the rotation ? when we use the lidar align imu data, why the translation have no influence?
3、I set 0 to make it unchange ,  if the translation is not accurate enough  , what it would be influence? 
4、what is the parameter mean below and what is the influence?
    keep_features:
    gravity_fix:

**Comment by hyye** [comment]
1. Larger window size will increase the execution time. A recommended window size is to cover the environment as large as possible but with the least number of frames.
2. You may refer to https://github.com/hyye/lio-mapping/issues/4#issuecomment-494632602 to find the way to do translation calibration. The translational part typically brings fewer effects on the initialization of our system, than the ones from the rotational part. And if auto calibration is on, the translation will converge if a reasonable initial value is given.
3. Yes.
4. `keep_features`: keep the previously calculated features or not, typically set it to `0`; `gravity_fix`: ignore it, debug only.
