### ISSUE TITLE
rviz only displays part of the map

### ISSUE THREAD

**Issue by shishiteng** [hyye/lio-mapping#27]
I have tested your code in a large environment and I can not see the whole map.  It seems rviz can only display part of it.

**Comment by yuer-h** [comment]
you can modify the decay time in rviz and can see the whole

**Comment by hyye** [comment]
Hi @shishiteng, @yuer-h gives a way to show a larger scale map in `rviz`.
For efficiency in larger environments, only several cubes of the whole map are used in the mapping.

**Comment by shishiteng** [comment]
Thank you guys @hyye @yuer-h ,I'll close this issue.
