### ISSUE TITLE
Supplementary Material

### ISSUE THREAD

**Issue by goldenminerlmg** [hyye/lio-mapping#3]
Hi anthor, nice Job ! Thank you for making this great work open source.

The document "Supplementary Material to-Tightly Coupled 3D Lidar Inertial Odometry and Mapping.pdf" can't be downloaded from the provided website. Can you uploaded it to github?

Thank you very much!

**Comment by hyye** [comment]
Hi @goldenminerlmg, can you check [this link](https://drive.google.com/file/d/1GW4RL8J3tfZWgIuOrBG1CBzat31y1TRQ/view)?  I've also updated our lab website.

**Comment by goldenminerlmg** [comment]
Hi @hyye  Thank you very much! This link can be opened!
