### ISSUE TITLE
It seems that lidar undistortion does not implement?

### ISSUE THREAD

**Issue by shishiteng** [hyye/lio-mapping#31]
Hi,I found that the function ‘PointProcessor::DeSkew()’ does not implement in the code. But in your paper you said  LIO can provide better performance with motion compensation.Does it mean  the result could be better If I do the undistortion by myself?

**Comment by hyye** [comment]
Hi @shishiteng, you may find more information at https://github.com/hyye/lio-mapping/issues/23#issuecomment-515310468.
