### ISSUE TITLE
how to get a dense map

### ISSUE THREAD

**Issue by zorosmith** [hyye/lio-mapping#35]
Hello, I want to get a dense map so I modify values in these files. However, the map is not as dense as those of other schemes(aloam, lego-loam).

In map_builder_node.cc, I reset the value as following, 
`MapBuilderConfig config;
  config.map_filter_size = 0.01`

In MapBuilder.h, I reset values as following, 
'struct MapBuilderConfig {
  float corner_filter_size = 0.01;
  float surf_filter_size = 0.01;
  float map_filter_size = 0.6;

  float min_match_sq_dis = 1.0;
  float min_plane_dis = 0.2;
};'

In Estimator.h, I reset values as following, 
`  float corner_filter_size = 0.01;
  float surf_filter_size = 0.01;
  float map_filter_size = 0.01;`

![image](https://user-images.githubusercontent.com/22607041/64468149-8546a100-d153-11e9-9cb2-7c8e30df1c17.png)

I guess there are 2 reasons.
1. I miss some parameters.
2. The raw point cloud is over-segmentation so that a small number points make up the map.
Could you give me some help?
Thank you!

**Comment by hyye** [comment]
For a dense map, I suggest to record the data and refer to https://github.com/hyye/lio-mapping/issues/9#issuecomment-505382679 to build a map.
