### ISSUE TITLE
Discrete time noise covariance

### ISSUE THREAD

**Issue by andre-nguyen** [hyye/lio-mapping#36]
Hi,

thank you so much for answering questions :smile:. In VINS-Mono the discrete time noise covariance matrix is approximated to the first order using
![image](https://user-images.githubusercontent.com/6036318/64873430-0b149180-d617-11e9-828a-b107a37945b0.png)

So `dt * Gt * Qt * Gt'` however in your supplementary material your approximation of `Qd` is
![image](https://user-images.githubusercontent.com/6036318/64873531-4747f200-d617-11e9-9d56-d35de3ff96a3.png)

Where does the extra dt come from?

**Comment by hyye** [comment]
This is from another convention of discretization.
I discussed with the author of VINS-Mono. The first one is more proper. I will change the supplementary material accordingly.

**Comment by andre-nguyen** [comment]
Interesting, do you know the reference? I think you can leave it like that in your supplementary material because that is how you did it in the code.

**Comment by hyye** [comment]
For the first one, [this paper](https://ieeexplore.ieee.org/stamp/stamp.jsp?tp=&arnumber=6018993) can be a reference.
For the second one, I cannot find a more official paper.

**Comment by andre-nguyen** [comment]
Thanks!
