### ISSUE TITLE
Confused with constraints part

### ISSUE THREAD

**Issue by getupgetup** [hyye/lio-mapping#37]
Hi, I'm new in LIO/VIO. According to your paper, I think the most different part between LIO and LOAM is the constraint/factor construction. I found this in your paper:
![1](https://user-images.githubusercontent.com/10446834/65132168-17dc1f80-da33-11e9-929f-ffcb4ed4c36e.png)
In my opinion,  LOAM simply use IMU data to give a predicted pose and focus on the second part of it. LIO add frame-to-frame pose constraint by IMU pre-integration. Am I right?
Threrefore, I'm confused with these constraints. the second part represents point-to-plane residuals and third part represents pose-to-pose residuals. Why can they be "added"? How to determine their covariance? Thank you~

**Comment by hyye** [comment]
This is the pre-integration term, as shown in [supplementary material](https://drive.google.com/file/d/1GW4RL8J3tfZWgIuOrBG1CBzat31y1TRQ/view) Eqn. (C.8), not pose-to-pose residuals.

**Comment by getupgetup** [comment]
> This is the pre-integration term, as shown in [supplementary material](https://drive.google.com/file/d/1GW4RL8J3tfZWgIuOrBG1CBzat31y1TRQ/view) Eqn. (C.8), not pose-to-pose residuals.

Thank you! Is this part mainly in function: Estimator::SolveOptimization()?
