### ISSUE TITLE
Do you test on the kitti dataset

### ISSUE THREAD

**Issue by Auto-RunningWang** [hyye/lio-mapping#41]
hello:
      What's the result of testing on kitti? How Lio-mapping ranking on that

**Comment by hyye** [comment]
Since KITTI doesn't provide high-frequency IMU data in the test sets, our method cannot be evaluated on this dataset. I tested on several KITTI training sets where our approach still worked.

**Comment by Auto-RunningWang** [comment]
Thanks for your response. I tested lio on several KITTI raw data sequences(100hz imu and 10hz lidar), the result show that pure lidar odometry (64_scans_test.launch) can work well but with imu tight coupling(test_outdoor_64.launch) it can not work well. I am confused if i did the wrong congfig or this algorithm can not deal with this dataset?
