### ISSUE TITLE
Questions about MapBuilder

### ISSUE THREAD

**Issue by getupgetup** [hyye/lio-mapping#42]
I noticed that global mapping can align with gravity because of refinement with rotational constraints. However, I still can't understand this part by your paper and the code in MapBuilder. Can you explain this part a bit more detailly~ Thank you!

**Comment by hyye** [comment]
Could you point out which part you didn't understand? Some derivations in the [supplementary material](https://drive.google.com/file/d/1GW4RL8J3tfZWgIuOrBG1CBzat31y1TRQ/view) may help.

**Comment by getupgetup** [comment]
Thanks~
