### ISSUE TITLE
OpenCV/CUDA might slow down the application

### ISSUE THREAD

**Issue by geoeo** [hyye/lio-mapping#52]
Hey,

I was running into issues with the (local) estimator node not achieving the performance it has on docker. The culprit seems to be opencv/cuda. When reading in the yaml file you use opecv to convert to Eigen. This uses CUDA behind the scenes, which somehow impacts performance negatively. 

This seems like a setup problem but I wanted to let you know this is an issue

**Comment by hyye** [comment]
Thanks, @geoeo.
