### ISSUE TITLE
Robot test

### ISSUE THREAD

**Issue by njauwangkai** [hyye/lio-mapping#53]
Hi i have some questions and would like to ask you，I run lio-map with a handheld device and it works.But I installed the device on a crawler robot and it didn't work.I would like to inquire what initial driving you did when you installed the laser and inertial navigation on the golf cart.When the esrltimate_extrinsic parameter is 1, the external parameters are basically accurate. Do I need to turn when starting?   thank you

**Comment by hyye** [comment]
Hi @njauwangkai, for some planar motion tests, the initialization process can be different. If you want to use this release of code, it is suggested to make a turn at the beginning to initialize the system. It is also possible to modify the initialization part to a static version.

**Comment by njauwangkai** [comment]
thank you very much  !  would you like tell me more detail about satatic version?  whether esrltimate_extrinsic parameter is 0? or the  information from the VINS-mono?
