### ISSUE TITLE
High default noise parameters

### ISSUE THREAD

**Issue by lsdta** [hyye/lio-mapping#56]
I find that the IMU noise parameters affect odometry significantly, has anyone experimented with these values? (given that they are from VINS-mono). Lowering the values seems to give more weighting to the IMU for odometry, and vice-versa. 

The default values of `acc_n = 0.2` and `gyr_n = 0.02` are quite high (a magnitude or two higher) compared to the noise values I found with [this repo](https://github.com/gaowenliang/imu_utils) as per #39, is this done on purpose?

**Comment by hyye** [comment]
Is the repo you mentioned providing the continuous-time noise? [IMU-Noise-Model](https://github.com/ethz-asl/kalibr/wiki/IMU-Noise-Model) can be another reference. Theoretically, these values should be obtained by calibration or empirically set for each sensor. The `yaml` file is an example of the configuration.

**Comment by lsdta** [comment]
I empirically calculated the noise values for my own sensor, and found that the `acc_w` and `gyr_w` values were of similar magnitude to your default values in the config files. However, the `acc_n` and `gyr_n` values were a magnitude or two lower in my tests vs your default values. The repo also provides their calculated parameters for the IMU you used [here](https://github.com/gaowenliang/imu_utils/blob/master/data/xsens_imu_param.yaml), which agree with my tests.

If you chose the high `acc_n` and `gyr_n` values [in your config files](https://github.com/hyye/lio-mapping/blob/master/config/outdoor_test_config.yaml#L58) through SLAM testing rather than noise measurements, then that's understandable, I am just looking to understand why as these are important parameters when it comes to tweaking outputs.
