### ISSUE TITLE
some doubts about process died

### ISSUE THREAD

**Issue by yuqingyang888** [hyye/lio-mapping#6]
I was playing a dataset recorded by myself. In the first 20seconds, it ran well. However, after that, something got wrong, and I didn't know how to fix it.
The dataset was recorded outside door, and when I used "test_indoor.launch" and "test_outdoor.launch". The mistake was the same.

![2019-05-27 19-25-57屏幕截图](https://user-images.githubusercontent.com/36471232/58416961-d9061080-80b5-11e9-87d1-4b66ecf46b11.png)

**Comment by hyye** [comment]
Could you please provide more detailed information about the crash? 

What is your IMU output rates? Did the system begin to drift before the crash?

**Comment by yuqingyang888** [comment]
The output rate is 200Hz.
The system indeed began to drift. The picture is a comparison between loam and lio. The LOAM seems operate normally.
![漂](https://user-images.githubusercontent.com/36471232/58419710-e9ba8480-80bd-11e9-8f29-076dc74d50e3.png)
![loam](https://user-images.githubusercontent.com/36471232/58419716-ede6a200-80bd-11e9-9a61-fde31553bc9e.png)

**Comment by hyye** [comment]
If it is planar motion, the current IMU initialization needs some rotation; and in the planar case, the extrinsic parameter estimation can be degenerate.

Perhaps you may try with outdoor config without initial guess of extrinsic parameters (set the flag in config file to 2, and the translational part of extrinsic parameters close to your sensor configuration).

**Comment by yuqingyang888** [comment]
I would try to solve it tomorrow. 
And I have another problem that there are two files where I could set the parameters.They are "indoor_test_config.yaml" and "Estimator.h". I should set the parameters in indoor_test_config.yaml. Is that correct?

**Comment by hyye** [comment]
You’re right, in the yaml file.

**Comment by hyye** [comment]
See more at https://github.com/hyye/lio-mapping/issues/11#issuecomment-508896635.
