### ISSUE TITLE
Problem about  groud truth lidar coordinate transformation

### ISSUE THREAD

**Issue by windwolf9** [hyye/lio-mapping#61]
Hi @hyye ,when using ground truth pose from topic "/Robot_7/pose" for estimating poses from lio-mapping, certain transformation between lidar and Twgt  is missing. Transformation in ReadME.md packed inside dataset won't work. Can you please provide this transformation? Thank you.

**Comment by hyye** [comment]
Hi @windwolf9, you may consider aligning two trajectories using the alignment tools from [rgbd-dataset/tools](https://vision.in.tum.de/data/datasets/rgbd-dataset/tools).
