### ISSUE TITLE
can't access the Supplementary Material in reference[12]

### ISSUE THREAD

**Issue by xieqi1** [hyye/lio-mapping#67]
The Supplementary Material which in https://sites.google.com/view/lio-mapping can't be accessible, I can't wait to read this material to help me better understand this excellent work. so is there any other way to get it? Thank you!

**Comment by DarrenWong** [comment]
seems direct pdf cannot be uploaded, unzip the file you can view the supplementary materials.  你需要一把梯子...

[Supplementary Material to-Tightly Coupled 3D Lidar Inertial Odometry and Mapping.pdf.zip](https://github.com/hyye/lio-mapping/files/4741257/Supplementary.Material.to-Tightly.Coupled.3D.Lidar.Inertial.Odometry.and.Mapping.pdf.zip)

**Comment by xieqi1** [comment]
get it ! Thank you very much ! 笔芯

**Comment by xieqi1** [comment]
it seems the link can be directly accessible today~
