### ISSUE TITLE
q_L and q_R typo in math_utils.h ?

### ISSUE THREAD

**Issue by narutojxl** [hyye/lio-mapping#69]
Hi @hyye thanks for your excellent work :)
* The rotation convention in your code is Hamilton, correct? 
*  q_L and q_R matrix in math_utils.h is JPL?

Thanks for your help!

**Comment by hyye** [comment]
Hi @narutojxl,
Thanks for your question. The conversion is all in Hamilton as Eigen's.

**Comment by narutojxl** [comment]
In [joan's paper](https://arxiv.org/pdf/1711.02508.pdf), his rotation is also Hamilton.
![2020-06-19 17-53-44屏幕截图](https://user-images.githubusercontent.com/6205343/85120630-1b1c6a00-b256-11ea-9a5d-e0620349bd13.png)
In math_utils.h
>
	template<typename Derived>
	inline Eigen::Matrix<typename Derived::Scalar, 4, 4> LeftQuatMatrix(const Eigen::QuaternionBase<Derived> &q) {
	  Eigen::Matrix<typename Derived::Scalar, 4, 4> m;
	  Eigen::Matrix<typename Derived::Scalar, 3, 1> vq = q.vec();
	  typename Derived::Scalar q4 = q.w();
	  m.block(0, 0, 3, 3) << q4 * I3x3 + SkewSymmetric(vq);
	  m.block(3, 0, 1, 3) << -vq.transpose();
	  m.block(0, 3, 3, 1) << vq;
	  m(3, 3) = q4;
	  return m;
	}
The code doesn't consistent with above definition?

**Comment by hyye** [comment]
I think it is exactly the same, except the order of the quaternion, right?

**Comment by narutojxl** [comment]
`q_L in code is: `
![1](https://user-images.githubusercontent.com/6205343/103882860-607f8680-5117-11eb-86d6-e8797155ed05.png)

`joan q_L is:`
![2](https://user-images.githubusercontent.com/6205343/103882904-6ecda280-5117-11eb-9760-c294769b55a1.png)

I don't understand why they are the same, right? :)

**Comment by hyye** [comment]
Since the orders of the coefficients are different. If you swap `q_v` and `q_w`, these two matrices are the same, right???

**Comment by narutojxl** [comment]
Hi @hyye, thanks for your patience with me :), thanks a lot ! 
* I see the eigen doc about quaternion's `vec()` function. It returns the imaginary part(q_x, q_y, q_z), matching joan's quaternion definition(q_w is scalar part, [q_x, q_y, q_z] is imaginary part). 
*  `x(), y(), z()` return the x, y, z coefficient respectively of quaternion. `w()` return the w coefficient.
![2020-06-22 11-00-35屏幕截图](https://user-images.githubusercontent.com/6205343/85244564-a32d8a00-b477-11ea-80e8-c786357e58aa.png)
