### ISSUE TITLE
this mehtod can named tight couple method ???

### ISSUE THREAD

**Issue by chennuo0125-HIT** [hyye/lio-mapping#83]
from the paper provided by readme, i found state to optimized just has (p v q ba bg), no environment feature. should include feature in state in couple method ???

**Comment by zhh2005757** [comment]
> from the paper provided by readme, i found state to optimized just has (p v q ba bg), no environment feature. should include feature in state in couple method ???

lio-sam seems more loosely coupled than this, but they named tightly coupled too😂

**Comment by hyye** [comment]
> from the paper provided by readme, i found state to optimized just has (p v q ba bg), no environment feature. should include feature in state in couple method ???

Well, both the 3D features and IMU measurements are considered in the optimizer. Following the definition in page 20 (https://rpg.ifi.uzh.ch/docs/teaching/2019/13_visual_inertial_fusion.pdf)[13_visual_inertial_fusion.pdf], it can be considered as a tightly-coupled method without involving the feature states directly in the optimizer. The map would still be updated in the odometry module. Hope this clarifies your concern.
